OrderFoodTeam/Models/Product.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace OrderFoodTeam.Models
{
    public class Product
    {
        [Key]
        public int Id { get; set; }

        public string Name { get; set; }
        public int Price { get; set; }
        public string Description { get; set; }

        public ProductEnum ProductEnum { get; set; }
        public MeasurementEnum MeasurementEnum { get; set; }

        public int Measurement { get; set; }
        public Image Image { get; set; } 
       
    }
   
    public enum ProductEnum : byte
    {
        Dish,
        Drink
    };
    public enum MeasurementEnum : byte
    {
        Gramm,
        Liter
    }
}

OrderFoodTeam/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OrderFoodTeam;
using OrderFoodTeam.Models;

namespace OrderFoodTeam.Controllers
{
    public class ProductController : Controller
    {
        private const int PAGE_SIZE = 6;
        private readonly AppDbContext _context;

        public ProductController(AppDbContext context)
        {
            _context = context;
        }
       
        // GET: Product
        //[Authorize(Roles = "admin")]
        public ActionResult Menu(int page = 1, int productIdentity = 2)
        {
            
            var Product = new List<Product>();
            ProductEnum valueDish = ProductEnum.Dish;
            ProductEnum valueDrink = ProductEnum.Drink;
            ViewBag.CurrentPage = page;
            //ViewBag.ProductIdentity = productIdentity;
            int count;
            if (productIdentity == 0)
            {
                Product = _context.Product.Include(i => i.Image)
                      .Where(p => p.ProductEnum == valueDish)
                      .OrderBy(p => p.Id).Skip((page - 1) * PAGE_SIZE)
                      .Take(PAGE_SIZE)
                      .ToList();
                count = _context.Product.Where(p => p.ProductEnum == valueDish).Select(i => i.Id).Count();
              
            }
            else if (productIdentity == 1)
            {
                Product = _context.Product.Include(i => i.Image)
                   .Where(p => p.ProductEnum == valueDrink)
                   .OrderBy(p => p.Id)
                   .Skip((page - 1) * PAGE_SIZE)
                   .Take(PAGE_SIZE).ToList();
                count = _context.Product.Where(p => p.ProductEnum == valueDrink).Select(i => i.Id).Count();
               
            }
            else 
            {
                Product = _context.Product.Include(i => i.Image).
                      OrderBy(p => p.Id).Skip((page - 1) * PAGE_SIZE).
                      Take(PAGE_SIZE).
                      ToList();
                count = _context.Product.Select(i => i.Id).Count();
               
            }
            //ViewBag.CurrentPage = page;
            ViewBag.ProductIdentity = productIdentity;
            //var count = _context.Product.Select(i => i.id).Count();
            ViewBag.PageCount = (int)Math.Ceiling((double)count / PAGE_SIZE);
            return View(Product);
        }

        // GET: Product/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Product
                .FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: Product/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Product/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,Name,Price,Description,ProductEnum,MeasurementEnum,Measurement")] Product product)
        {
            if (ModelState.IsValid)
            {
                _context.Add(product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }

        // GET: Product/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Product.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }

        // POST: Product/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,Name,Price,Description,ProductEnum,MeasurementEnum,Measurement")] Product product)
        {
            if (id != product.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(product);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Menu));
            }
            return View(product);
        }

        // GET: Product/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Product
                .FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Product/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var product = await _context.Product.FindAsync(id);
            _context.Product.Remove(product);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductExists(int id)
        {
            return _context.Product.Any(e => e.Id == id);
        }
    }
}

OrderFoodTeam/Controllers/ShopCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using OrderFoodTeam.Models;
using OrderFoodTeam.ViewModel;

namespace OrderFoodTeam.Controllers
{
    public class ShopCartController : Controller
    {
       private readonly ShopCart _shopCart;

        private readonly AppDbContext _context;

        public ShopCartController(AppDbContext context, ShopCart shopCart)
        {
            _context = context;
            _shopCart = shopCart;
        }

      

        public ViewResult Index()
        {
            var items = _shopCart.getShopItems();
            _shopCart.ListShopItems = items;
            var obj = new ShopCartViewModel
            {
                shopCart = _shopCart
            };
            return View(obj);

        }
        public RedirectToActionResult addToCart(int id)
        {
            var item = _context.Product.FirstOrDefault(i => i.Id == id);
            if(item != null)
            {
                _shopCart.AddToCart(item,1);
            }
            return RedirectToAction("Index");
                
        }
        public RedirectToActionResult RemoveFromShoppingCart(int id)
        {
            var item = _context.Product.FirstOrDefault(i => i.Id == id);
            if (item != null)
            {
                _shopCart.RemoveFromCart(item);
            }
            return RedirectToAction("Index");

        }



    }
}

OrderFoodTeam/Views/Product/Create.cshtml
@model OrderFoodTeam.Models.Product

@{
    ViewData["Title"] = "Create";
}

<div class="white_container register_container nav_top_menu" id="create">
    <div class="container">
        <div class="row">
            <div class="col-md-12">


                <div class="registerMylass">
                    <h2>Create</h2>
                </div>
                <hr />
                <div class="row item_delete">
                    <div class="">
                        <form asp-action="Create">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <div class="form-group">
                                <label asp-for="Name" class="control-label"></label>
                                <input asp-for="Name" class="form-control" />
                                <span asp-validation-for="Name" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Price" class="control-label"></label>
                                <input asp-for="Price" class="form-control" />
                                <span asp-validation-for="Price" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Description" class="control-label"></label>
                                <input asp-for="Description" class="form-control" />
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="ProductEnum" class="control-label"></label>
                                <select asp-for="ProductEnum" class="form-control"></select>
                                <span asp-validation-for="ProductEnum" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="MeasurementEnum" class="control-label"></label>
                                <select asp-for="MeasurementEnum" class="form-control"></select>
                                <span asp-validation-for="MeasurementEnum" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Measurement" class="control-label"></label>
                                <input asp-for="Measurement" class="form-control" />
                                <span asp-validation-for="Measurement" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <input type="submit" value="Create" class="btn btn-primary" />
                            </div>
                        </form>
                        <div style="text-align:center">
                            <a asp-action="Menu" class="btn btn-primary ">Back to List</a>
                        </div>
                    </div>
                </div>

               

            </div>
        </div>
    </div>
</div>

OrderFoodTeam/Views/Product/Delete.cshtml
@model OrderFoodTeam.Models.Product

@{
    ViewData["Title"] = "Delete";
}


<div class="white_container register_container nav_top_menu" id="delete">
    <div class="container">
        <div class="row">
            <div class="col-md-12"> 
                <h2>Delete</h2>
                <hr>
                <div class="registerMylass">
                    <h4>Are you sure you want to delete this?</h4>
                </div>
                <div class="item_delete">
                    
                        <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.Name)
                        </dt>
                        <dd style="color:darkorange;font-weight:800;">
                            @Html.DisplayFor(model => model.Name)
                        </dd>
                        <dt>
                            @Html.DisplayNameFor(model => model.Price)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.Price)
                        </dd>
                        <dt>
                            @Html.DisplayNameFor(model => model.Description)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.Description)
                        </dd>
                        <dt>
                            @Html.DisplayNameFor(model => model.ProductEnum)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.ProductEnum)
                        </dd>
                        <dt>
                            @Html.DisplayNameFor(model => model.MeasurementEnum)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.MeasurementEnum)
                        </dd>
                        <dt>
                            @Html.DisplayNameFor(model => model.Measurement)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.Measurement)
                        </dd>
                    </dl>

                    <form asp-action="Delete" class="button_delete">
                        <input type="hidden" asp-for="Id" />
                        <input type="submit" value="Delete" class="btn btn-primary" /> 
                        <a asp-action="Index" class="btn btn-primary">Back to List</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

OrderFoodTeam/Views/Product/Details.cshtml
@model OrderFoodTeam.Models.Product

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Product</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ProductEnum)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ProductEnum)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.MeasurementEnum)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MeasurementEnum)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Measurement)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Measurement)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

OrderFoodTeam/Views/Product/Edit.cshtml
@model OrderFoodTeam.Models.Product

<div class="white_container register_container nav_top_menu" id="edit">
<div class="container">
    <div class="row">
        <div class="col-md-12">


            <div class="registerMylass">
                <h2>Edit</h2>
                </div>

                <hr />

                <div class="row item_delete">

                    <div class="">
                        <form asp-action="Edit">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <input type="hidden" asp-for="Id" />
                            <div class="form-group">
                                <label asp-for="Name" class="control-label"></label>
                                <input asp-for="Name" class="form-control" />
                                <span asp-validation-for="Name" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Price" class="control-label"></label>
                                <input asp-for="Price" class="form-control" />
                                <span asp-validation-for="Price" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Description" class="control-label"></label>
                                <input asp-for="Description" class="form-control" />
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="ProductEnum" class="control-label"></label>
                                <select asp-for="ProductEnum" class="form-control">
                                    <option value="0">Food</option>
                                    <option value="1">Drink</option>
                                </select>
                                <span asp-validation-for="ProductEnum" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="MeasurementEnum" class="control-label"></label>
                                <select asp-for="MeasurementEnum" class="form-control">
                                    <option value="0">Gramm</option>
                                    <option value="1">Litr</option>
                                </select>
                                <span asp-validation-for="MeasurementEnum" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Measurement" class="control-label"></label>
                                <input asp-for="Measurement" class="form-control" />
                                <span asp-validation-for="Measurement" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <input type="submit" value="Save" class="btn btn-primary" asp-fragment="menu" />
                            </div>
                        </form>
                        <div style="text-align:center">
                            <a asp-action="Menu" asp-fragment="menu" class="btn btn-primary" >Back to List</a>
                        </div>
                    </div>
                </div>

               

            </div>
        </div>
</div>
</div>

OrderFoodTeam/Views/Product/Index.cshtml
@model IEnumerable<OrderFoodTeam.Models.Product>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProductEnum)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MeasurementEnum)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Measurement)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProductEnum)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MeasurementEnum)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Measurement)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

OrderFoodTeam/Views/Product/Menu.cshtml
@using Microsoft.AspNetCore.Identity
@inject UserManager<IdentityUser> UserManager
@model IEnumerable<OrderFoodTeam.Models.Product>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Menu";
}
@{

    var currentLink = $"/Product/Menu?page={ViewBag.CurrentPage}";
    


}
<div class="menu nav_top_menu" id="menu">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h2>@ViewBag.Title</h2>
                <hr>
                @if (User.IsInRole("admin"))
                {
                    <p class="btn_create_product">
                        <!---->
                        <a asp-action="Create" class="btn btn-primary btn_create_product" asp-fragment="create">Create New</a>
                    </p>
                }

                @if (ViewBag.ProductIdentity == 2)
                {
                    <div class="category_product">
                        <a href="/product/menu?page=@(ViewBag.CurrentPage)&productIdentity=2#MenuItem" class="btn btn-primary is-active">All</a>
                        <a href="/product/menu?page=@(ViewBag.CurrentPage)&productIdentity=0#MenuItem" class="btn btn-primary">Food</a>
                        <a href="/product/menu?page=@(ViewBag.CurrentPage)&productIdentity=1#MenuItem" class="btn btn-primary">Drink</a>

                    </div>
                }
                else if (ViewBag.ProductIdentity == 1)
                {
                    <div class="category_product">
                        <a href="/product/menu?page=@(ViewBag.CurrentPage)&productIdentity=2#MenuItem" class="btn btn-primary">All</a>
                        <a href="/product/menu?page=@(ViewBag.CurrentPage)&productIdentity=0#MenuItem" class="btn btn-primary">Food</a>
                        <a href="/product/menu?page=@(ViewBag.CurrentPage)&productIdentity=1#MenuItem" class="btn btn-primary is-active">Drink</a>

                    </div>
                }
                else
                {
                    <div class="category_product">
                        <a href="/product/menu?page=@(ViewBag.CurrentPage)&productIdentity=2#MenuItem" class="btn btn-primary">All</a>
                        <a href="/product/menu?page=@(ViewBag.CurrentPage)&productIdentity=0#MenuItem" class="btn btn-primary is-active">Food</a>
                        <a href="/product/menu?page=@(ViewBag.CurrentPage)&productIdentity=1#MenuItem" class="btn btn-primary ">Drink</a>

                    </div>

                }
                <div class="row nav_top_product" id="MenuItem">
                    <div class="block_Product">
                        @foreach (var item in Model)
                        {

                            <div class="col-md-4">

                                <div class="itemMenu">



                                    <div class="col-md-12">
                                        <img src="~/img/@item.Image.Url" alt="Alternate Text" class="img-thumbnail center-block" />
                                    </div>

                                    <h5>@Html.DisplayFor(modelItem => item.Name)</h5>
                                    <p class="description">
                                        @Html.DisplayFor(modelItem => item.Description)
                                    </p>
                                    <div class="measurment"><h6>Measurment :<span>@Html.DisplayFor(modelItem => item.Measurement)</span></h6></div>

                                    <div class="price"><h6>Price :<span>@Html.DisplayFor(modelItem => item.Price)</span></h6></div>
                                    <a class="btn btn-primary center-block add_to_cart" asp-controller="ShopCart" asp-action="addToCart" asp-route-id="@item.Id" asp-fragment="basket" style="margin: 10px auto; display:table">Add to cart</a>



                                    @if (User.IsInRole("admin"))
                                    {
                                        <div class="but_edit_delete">
                                            <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-primary" asp-fragment="edit">Edit</a>
                                            <!--<a asp-action="Details" asp-route-id="@item.Id">Details</a>-->
                                            <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-primary" asp-fragment="delete">Delete</a>
                                        </div>
                                    }


                                </div>

                            </div>

                        }
                    </div>
                </div>
                <tr>
                    <td colspan="8" class="text-center">
                        <ul class="pagination">
                            @if (ViewBag.CurrentPage == 1)
                            {
                                <li class="page-item disabled"><span class="page-link">Previous</span></li>
                            }
                            else
                            {
                                <li class="page-item"><a class="page-link" href="/product/menu?page=@(ViewBag.CurrentPage - 1)&productIdentity=@(ViewBag.ProductIdentity)#MenuItem">Previous</a></li>
                            }
                            @for (int i = 1; i <= ViewBag.PageCount; i++)
                            {
                                if (i == ViewBag.CurrentPage)
                                {
                                    <li class="page-item active"><span class="page-link"> @i<span class="sr-only">(current)</span></span></li>
                                }
                                else
                                {
                                    <li class="page-item"><a class="page-link" href="/product/menu?page=@i&productIdentity=@(ViewBag.ProductIdentity)#MenuItem">@i</a></li>
                                }
                            }
                            @if (ViewBag.CurrentPage == ViewBag.PageCount)
                            {
                                <li class="page-item disabled"><span class="page-link">Next</span></li>
                            }
                            else
                            {
                                <li class="page-item"><a class="page-link" href="/product/menu?page=@(ViewBag.CurrentPage + 1)&productIdentity=@(ViewBag.ProductIdentity)#MenuItem">Next</a></li>
                            }
                        </ul>
                    </td>
                </tr>

            </div>
        </div>
    </div>
</div>