OrderFoodTeam/Models/Order.cs
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace OrderFoodTeam.Models
{
    public class Order
    {
        [Key]
        public int Id { get; set; }
      
        [Display(Name = "Town")]
        [Required(ErrorMessage = "Lengths of Town have to more tnan 2 letters")]
        public string Town { get; set; }
        [Display(Name = "Street")]
        [Required(ErrorMessage = "Lengths of Address have to more tnan 2 letters")]
        public string Street { get; set; }
        [Display(Name = "HomeNumber")]
        [Required(ErrorMessage = "Lengths of Address hava to more tnan 1 letters")]
        public string HomeNumber { get; set; }

        public DateTime OrderTime { get; set; }

       
        public Collection<OrderDetail> OrderDetail { get; set; }

    }
}

OrderFoodTeam/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Providers.Entities;
using Microsoft.AspNet.Identity;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using OrderFoodTeam.Models;

namespace OrderFoodTeam.Controllers
{
    public class OrderController : Controller
    {
        private readonly AppDbContext _context;
        private readonly ShopCart _shopCart;
      // private readonly Product _product;
        private readonly SignInManager<IdentityUser> _signInManager;
        //private readonly UserManager<IdentityUser> _userManager;

        public OrderController(AppDbContext context, ShopCart shopCart, SignInManager<IdentityUser> signInManager)
        {
            _context = context;
            _shopCart = shopCart;
            _signInManager = signInManager;
          
        }

        public ActionResult CreateOrder(Order order)
        {
            Product pr = new Product();
            
            if (_signInManager.IsSignedIn(User))
            {
               

                var userId = Guid.Parse((User.Identity.GetUserId()));
                order.OrderTime = DateTime.Now;
               
                _context.Order.Add(order);
                
            
            var items = _shopCart.ListShopItems;
            
                foreach(var element in items)
                {
                    var orderDetail = new OrderDetail()
                    {
                        Product = element.Product,
                        Order = order,
                        Price = element.Product.Price * element.Amount,
                        UserId = userId
                    };
                    _context.OrderDetail.Add(orderDetail);
                }
            }
            else
            {
                return Redirect($"/account/login");
            }
            _context.SaveChanges();
            return Redirect($"/menu");
        }
        public ActionResult Checkout()
        {

            return View();
        }
        public void DeleteOrder(Order order)
        {
           // _context.OrderDetail.Remove();
            _context.Order.Remove(order);
            _context.SaveChanges();
        }
        [HttpPost]
        public ActionResult Checkout(Order order)
        {
            _shopCart.ListShopItems = _shopCart.getShopItems();
            if(_shopCart.ListShopItems.Count == 0)
            {
                ModelState.AddModelError("","You need to have items");
            }
            if(ModelState.IsValid)
            {
                CreateOrder(order);
                HttpContext.Session.Clear();
                RemoveShopItems();
                //DeleteOrder(order);
                //
                // ShopCart.ClearSession()
                //ISession session = services.GetRequiredService<IHttpContextAccessor>()?.HttpContext.Session;
                return RedirectToAction("Complete");
            }
            return View(order);
        }
        public IActionResult Complete()
        {
            ViewBag.Message = "Successful";
            
            return View();
        }
        public void RemoveShopItems()
        {
            var items = _context.ShopCartItem
                .Where(c => c.ShopCartId == _shopCart.ShopCartId);
            foreach(var pr in items)
            {
                _context.ShopCartItem.Remove(pr);
              
            }
            _context.SaveChanges();



        }

    }
}

OrderFoodTeam/Controllers/OrderDetailController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace OrderFoodTeam.Controllers
{
    public class OrderDetailController : Controller
    {
        private readonly AppDbContext _context;
        public OrderDetailController(AppDbContext context)
        {
            _context = context;
        }
        public ActionResult Index()
        {
            var all = _context.OrderDetail.Include(i => i.Product).ToList();
            var test = _context.OrderDetail.Include(i => i.Order).ToList();
            return View(all);
        }
    }
}

OrderFoodTeam/Views/Order/Checkout.cshtml
@model OrderFoodTeam.Models.Order

@{
    ViewData["Title"] = "Create";
}

<div class="white_container register_container nav_top_menu" id="checkout">
    <div class="container">
        <div class="row">
            <div class="col-md-12">


                <div class="registerMylass">
                    <h2>Checkout</h2>
                </div>
                <hr />
                <div class="row item_delete">
                    <div class="">
                        <form asp-action="Checkout" method="post">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <div class="form-group">
                                <label asp-for="Town" class="control-label"></label>
                                <input asp-for="Town" class="form-control" />
                                <span asp-validation-for="Town" class="text-danger"></span>
                            </div>

                            <div class="form-group">
                                <label asp-for="Street" class="control-label"></label>
                                <input asp-for="Street" class="form-control" />
                                <span asp-validation-for="Street" class="text-danger"></span>
                            </div>

                            <div class="form-group">
                                <label asp-for="HomeNumber" class="control-label"></label>
                                <input asp-for="HomeNumber" class="form-control" />
                                <span asp-validation-for="HomeNumber" class="text-danger"></span>
                            </div>
                            <input class="btn btn-primary" type="submit" value="Confirm Pay" asp-fragment="complete"/>
                        </form>
                       
                    </div>
                </div>



            </div>
        </div>
    </div>
</div>

OrderFoodTeam/Views/Order/Complete.cshtml
<div class="white_container register_container nav_top_menu" id="complete">
    <div class="container">
        <div class="row">
            <div class="col-md-12">


                <div class="registerMylass">
                    <h2>@ViewBag.Message</h2>
                </div>
                <hr />

                <!--<a asp-action="Index" asp-controller="OrderDetail" class="btn btn-primary" asp-fragment="orderdetail">Show</a>-->


            </div>
        </div>
    </div>
</div>