OrderFoodTeam/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OrderFoodTeam;
using OrderFoodTeam.Models;

namespace OrderFoodTeam.Controllers
{
    public class ProductController : Controller
    {
        private const int PAGE_SIZE = 6;
        private readonly AppDbContext _context;

        public ProductController(AppDbContext context)
        {
            _context = context;
        }
       
        // GET: Product
        //[Authorize(Roles = "admin")]
        public ActionResult Menu(int page = 1, int productIdentity = 2)
        {
            
            var Product = new List<Product>();
            ProductEnum valueDish = ProductEnum.Dish;
            ProductEnum valueDrink = ProductEnum.Drink;
            ViewBag.CurrentPage = page;
            //ViewBag.ProductIdentity = productIdentity;
            int count;
            if (productIdentity == 0)
            {
                Product = _context.Product.Include(i => i.Image)
                      .Where(p => p.ProductEnum == valueDish)
                      .OrderBy(p => p.Id).Skip((page - 1) * PAGE_SIZE)
                      .Take(PAGE_SIZE)
                      .ToList();
                count = _context.Product.Where(p => p.ProductEnum == valueDish).Select(i => i.Id).Count();
              
            }
            else if (productIdentity == 1)
            {
                Product = _context.Product.Include(i => i.Image)
                   .Where(p => p.ProductEnum == valueDrink)
                   .OrderBy(p => p.Id)
                   .Skip((page - 1) * PAGE_SIZE)
                   .Take(PAGE_SIZE).ToList();
                count = _context.Product.Where(p => p.ProductEnum == valueDrink).Select(i => i.Id).Count();
               
            }
            else 
            {
                Product = _context.Product.Include(i => i.Image).
                      OrderBy(p => p.Id).Skip((page - 1) * PAGE_SIZE).
                      Take(PAGE_SIZE).
                      ToList();
                count = _context.Product.Select(i => i.Id).Count();
               
            }
            //ViewBag.CurrentPage = page;
            ViewBag.ProductIdentity = productIdentity;
            //var count = _context.Product.Select(i => i.id).Count();
            ViewBag.PageCount = (int)Math.Ceiling((double)count / PAGE_SIZE);
            return View(Product);
        }

        // GET: Product/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Product
                .FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: Product/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Product/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,Name,Price,Description,ProductEnum,MeasurementEnum,Measurement")] Product product)
        {
            if (ModelState.IsValid)
            {
                _context.Add(product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }

        // GET: Product/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Product.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }

        // POST: Product/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,Name,Price,Description,ProductEnum,MeasurementEnum,Measurement")] Product product)
        {
            if (id != product.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(product);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Menu));
            }
            return View(product);
        }

        // GET: Product/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Product
                .FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Product/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var product = await _context.Product.FindAsync(id);
            _context.Product.Remove(product);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductExists(int id)
        {
            return _context.Product.Any(e => e.Id == id);
        }
    }
}

OrderFoodTeam/Controllers/ReservationController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OrderFoodTeam.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNet.Identity;

namespace OrderFoodTeam.Controllers
{
    public class ReservationController : Controller
    {
        private readonly AppDbContext _context;
        public IActionResult Index()
        {
            return View();
        }
        public ReservationController(AppDbContext context)
        {

            _context = context;
        }

        public async Task<ActionResult> Submit(string people, string date, string time, string name, int table)
        {

            int p;
            
            Int32.TryParse(people, out p);
            var userId = Guid.Parse((User.Identity.GetUserId()));
            Reservation reserv = new Reservation { Quantity = p, ReservationDate = date, ReservationTime = time, FullName = name, NumberTable = table,UserId = userId };
            _context.Add(reserv);
            var ResTable = _context.Table
                .Where(c => c.id == table)
                .FirstOrDefault();

            // Внести изменения
            ResTable.Reserved = true;

            // Сохранить изменения
            await _context.SaveChangesAsync();

            return View(reserv);





        }
        public IActionResult Watch()
        {
            
         
                return View(_context.Reservation.ToList());
            
        }

        public IActionResult MyRes()
        {

            List<Reservation> UserReservs = new List<Reservation>();
            var Reserves = _context.Reservation.ToList();
            var userId = Guid.Parse((User.Identity.GetUserId()));

           

            foreach (var reserve in Reserves)
            {
                if (reserve.UserId == userId)
                {
                    UserReservs.Add(reserve);
                }
            }

            return View(UserReservs);



        }

        public IActionResult Delete(int? Id)
        {
            if (Id == null)
            {
                return NotFound();
            }

            var reserv = _context.Reservation
                .FirstOrDefault(m => m.Id == Id);
            if (reserv == null)
            {
                return NotFound();
            }

            return View(reserv);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int Id)
        {
            var reserv = await _context.Reservation.FindAsync(Id);
            
            _context.Reservation.Remove(reserv);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(MyRes));
        }

        /* public async Task<ActionResult> Delete(int id)
         {


             Reservation b = _context.Reservation.Find(id);
             if (b != null)
             {
                 _context.Reservation.Remove(b);

                 await _context.SaveChangesAsync();
             }
             var ResTable = _context.Table
            .Where(c => c.id == b.NumberTable)
            .FirstOrDefault();

             // Внести изменения
             ResTable.Reserved = false;

             // Сохранить изменения
             await _context.SaveChangesAsync();
             return RedirectToAction("MyRes");
         }*/
    }
}

OrderFoodTeam/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OrderFoodTeam</title>

    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700|Pinyon+Script" rel="stylesheet">
    <link href="~/css/styles-merged.css" rel="stylesheet" />
    <link href="~/css/style.css" rel="stylesheet" />


</head>
<body>

    <nav class="navbar navbar-default navbar-fixed-top probootstrap-navbar ">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.html" title="ProBootstrap:FineOak">FineOak</a>
            </div>

            <div id="navbar-collapse" class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li><a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Main</a></li>
                    <li> <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Menu">Menu</a></li>
                    <li> <a class="nav-link text-dark" asp-area="" asp-controller="Reservation" asp-action="Index">Reservation</a></li>
                    <li> <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Location">Location</a></li>


                    <partial name="_LoginPartial" />
                </ul>
            </div>
        </div>
    </nav>

    <section class="flexslider">
        <ul class="slides">
            <li style="background-image: url(/img/hero_bg_1.jpg)" class="overlay" data-stellar-background-ratio="0.5">
                <div class="container">
                    <div class="row">
                        <div class="col-md-8 col-md-offset-2">
                            <div class="probootstrap-slider-text text-center probootstrap-animate probootstrap-heading">
                                <h1 class="primary-heading">Welcome</h1>
                                <h3 class="secondary-heading">The Resto</h3>
                                <p class="sub-heading">A free bootstrap website template by <a href="https://probootstrap.com">ProBootstrap.com</a></p>
                            </div>
                        </div>
                    </div>
                </div>
            </li>
            <li style="background-image: url(/img/hero_bg_2.jpg)" class="overlay" data-stellar-background-ratio="0.5">
                <div class="container">
                    <div class="row">
                        <div class="col-md-8 col-md-offset-2">
                            <div class="probootstrap-slider-text text-center probootstrap-animate probootstrap-heading">
                                <h1 class="primary-heading">Dine</h1>
                                <h3 class="secondary-heading">With Us</h3>
                                <p class="sub-heading">A free bootstrap website template by <a href="https://probootstrap.com">ProBootstrap.com</a></p>
                            </div>
                        </div>
                    </div>
                </div>

            </li>
            <li style="background-image: url(/img/hero_bg_3.jpg)" class="overlay">
                <div class="container">
                    <div class="row">
                        <div class="col-md-8 col-md-offset-2">
                            <div class="probootstrap-slider-text text-center probootstrap-animate probootstrap-heading">
                                <h1 class="primary-heading">Enjoy</h1>
                                <h3 class="secondary-heading">With Us</h3>
                                <p class="sub-heading">A free bootstrap website template by <a href="https://probootstrap.com">ProBootstrap.com</a></p>
                            </div>
                        </div>
                    </div>
                </div>
            </li>
        </ul>
    </section>

    <main role="main" class="pb-3">
        @RenderBody()
    </main>

   
    <!---->
    <footer>
        <div class="container">
            <div class="col-md-12">
                <div class="row">
                    <div class="footer_text">
                        <p>Reservation Table in the <span style="color:#FFA33E;">best</span> restaurant</p>
                    </div>
                    <div class="col-md-4 left_block">
                        <p class="footer_address">Address:</p>
                        <address>Hebesnoi Sotni,34 Street</address>
                        <a href="mailto:youremailaddress">Email Me</a>
                    </div>
                    <div class="col-md-4">
                       
                            <p style="text-transform:uppercase; color:black">Our Store</p>
                            <span class="seperator">* * *</span>
                       
                        <p>Voluptatibus quaerat laboriosam fugit non Ut consequatur animi est molestiae enim a voluptate totam natus modi debitis dicta impedit voluptatum quod sapiente illo saepe explicabo quisquam perferendis labore et illum suscipit</p>
                        <p><a href="#">About Us</a></p>
                    </div>
                    <div class="col-md-4 list">
                        <ul class="list_footer">


                            <li><a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Main</a></li>
                            <li><a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Menu">Menu</a></li>
                            <li><a class="nav-link text-dark" asp-area="" asp-controller="Reservation" asp-action="Index">Reservation</a></li>
                            <partial name="_LoginPartial" />
                        </ul>

                       
                    </div>
                </div>
                <div class="footer_bot">Reservation Table.2019.&copy;</div> 
                
            </div>
        </div>
        <p align="right"><a href="www.facebook.com/bacaracoffee"style="color: black"></a></p>
        </footer>
   <!---->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/scripts.js"></script>
    <script src="~/js/custom.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

OrderFoodTeam/Views/Shared/_ReservePartial.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager


@if (SignInManager.IsSignedIn(User))
{
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage">Hello @User.Identity.Name!</a>
    </li>
    <li class="nav-item">
        <form class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
            <button type="submit" class="nav-link btn btn-link text-dark">Logout</button>
        </form>
    </li>
}
else
{
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="Reserve" asp-page="/Account/Login">Login</a>
    </li>
}